-- ============================================================================
-- crear_ventas_chef.sql   ·   PASO 1 de 3
-- Ventas históricas de CHEF (planilla Ventas_Chef.xlsx, may-2021 → jun-2026).
--
-- Flujo completo:
--   PASO 1: correr este script en el SQL editor (kwkclwhmoygunqmlegrg).
--   PASO 2: Table Editor → tabla `ventas_chef` → Insert → "Import data from CSV"
--           → subir ventas_chef.csv (37.548 filas; los headers mapean solos).
--   PASO 3: correr impactar_ventas_chef_en_sales_lines.sql (inserta las ventas
--           reales en sales_lines con empresa='chef').
--
-- Columnas del CSV (vienen de la planilla, que YA hizo la normalización):
--   cod        → código NORMALIZADO (columna C). Es el que impacta en las
--                estadísticas; para artículos Loeke ya es el código del catálogo.
--   cod_origen → código CRUDO del sistema Chef (columna H: 025L, 7098800, 708Z…).
--   estado     → '' (artículo Chef activo) · 'LK'/'Loekemeyer' (artículo del
--                catálogo Loekemeyer vendido vía Chef) · 'INACTIVO' (Chef
--                discontinuado) · 'NO CONSIDERAR' (basura: descuentos, serv, etc.)
-- Hay cajas NEGATIVAS (devoluciones): se cargan tal cual.
-- ============================================================================

-- 1) Staging: la planilla cruda completa (se conserva como fuente de verdad)
create table if not exists public.ventas_chef (
  id          bigint generated by default as identity primary key,
  fecha       date    not null,
  cod_cliente text    not null,
  cod         text    not null,
  cajas       numeric not null,
  estado      text,
  cod_origen  text
);
create index if not exists idx_ventas_chef_fecha   on public.ventas_chef (fecha);
create index if not exists idx_ventas_chef_cliente on public.ventas_chef (cod_cliente);
create index if not exists idx_ventas_chef_cod     on public.ventas_chef (cod);

-- Cerrada por RLS sin policies: nadie con anon/authenticated la lee (mismo
-- criterio que sales_lines: SQL editor, service_role o RPC SECURITY DEFINER).
alter table public.ventas_chef enable row level security;

-- 2) Equivalencias de códigos que la planilla ya aplicó (bloque N-O), como
--    referencia: crudo → normalizado. En el CSV la columna `cod` ya viene
--    con esto aplicado; NO hace falta re-aplicarlas.
create table if not exists public.chef_item_remap (
  from_code text primary key,
  to_code   text not null
);
alter table public.chef_item_remap enable row level security;
insert into public.chef_item_remap (from_code, to_code) values
  ('708Z',   '708'),
  ('830',    '438E'),
  ('828',    '437E'),
  ('438E-',  '438E'),
  ('437E-',  '437E'),
  ('367E-',  '367E'),
  ('544E',   '802'),
  ('877Eee', '877'),
  ('802E',   '802')
on conflict (from_code) do update set to_code = excluded.to_code;

-- 3) Códigos a NO considerar (bloque Q) — descuentos/servicios/basura.
create table if not exists public.chef_excluded_items (
  item_code text primary key
);
alter table public.chef_excluded_items enable row level security;
insert into public.chef_excluded_items (item_code) values
  ('P10%'), ('P23.5%'), ('serv'), ('DtovVol'), ('1101'),
  ('MF11'), ('MF12'), ('MF13'), ('MF14'), ('MF15'), ('MF16'),
  ('MF17'), ('MF18'), ('MF19'), ('MF20'), ('MF21'), ('MF22'),
  ('1'), ('99999'), ('999999')
on conflict (item_code) do nothing;

-- 4) Artículos ACTIVOS de Chef (columna L, 104 códigos).
create table if not exists public.chef_articulos_activos (
  cod text primary key
);
alter table public.chef_articulos_activos enable row level security;
insert into public.chef_articulos_activos (cod) values
  ('043'), ('052'), ('053'), ('054'), ('055'), ('097'), ('099'), ('307'),
  ('367E'), ('437E'), ('438E'), ('439E'), ('440E'), ('456'), ('609'), ('613'),
  ('615'), ('618'), ('619'), ('630'), ('631'), ('632'), ('633'), ('634'),
  ('635'), ('636'), ('637'), ('690E'), ('700'), ('701'), ('702E'), ('706'),
  ('707'), ('708'), ('709'), ('710'), ('712E'), ('713'), ('715'), ('717'),
  ('718'), ('719'), ('720'), ('722'), ('723'), ('725E'), ('727E'), ('729E'),
  ('730'), ('731'), ('732'), ('735'), ('755'), ('758'), ('759'), ('760'),
  ('761'), ('762'), ('763'), ('764'), ('769'), ('789'), ('798E'), ('800'),
  ('801'), ('802'), ('809E'), ('816'), ('817'), ('818'), ('824'), ('825'),
  ('836'), ('838E'), ('839'), ('840'), ('842'), ('843'), ('844'), ('845'),
  ('846'), ('847'), ('848'), ('852'), ('856'), ('857'), ('858'), ('859'),
  ('862'), ('863'), ('865E'), ('867'), ('878'), ('890E'), ('900'), ('901'),
  ('902'), ('908'), ('909'), ('910'), ('911'), ('920'), ('922'), ('977')
on conflict (cod) do nothing;

-- Verificación post-import del CSV (correr después del PASO 2):
--   select count(*) filas, min(fecha) desde, max(fecha) hasta,
--          count(distinct cod_cliente) clientes, count(distinct cod) codigos
--   from ventas_chef;
-- Esperado: 37548 filas · 2021-05-03 → 2026-06-30 · 333 clientes · 422 códigos.
